services:
  # All-in-one service: Streamlit app, Redis, and Celery worker
  app:
    build: .
    container_name: ma-data-app
    ports:
      - "8080:8080"
      - "6379:6379"
      - "2222:22"  # SSH access
    environment:
      - REDIS_URL=redis://localhost:6379/0
      - CELERY_BROKER_URL=redis://localhost:6379/0
      - CELERY_RESULT_BACKEND=redis://localhost:6379/0
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      - redis_data:/var/lib/redis
    restart: unless-stopped

volumes:
  redis_data: